# Generated by Django 5.1.4 on 2025-01-27 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(default=None, max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('number_of_entries', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(default=None, null=True)),
                ('email', models.TextField(default=None, null=True)),
                ('password', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.TextField(default=None)),
                ('max_score', models.IntegerField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('difficulty_level', models.TextField(default=None)),
                ('problem_statement', models.TextField(default=None)),
                ('constraints', models.TextField(default=None)),
                ('input_form', models.TextField(default=None)),
                ('output_form', models.TextField(default=None)),
                ('testcase', models.FileField(default=None, null=True, upload_to='testcase/')),
                ('output', models.FileField(default=None, null=True, upload_to='output/')),
                ('sample_testcase', models.TextField(default=None, null=True)),
                ('sample_output', models.TextField(default=None, null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.contest')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.user'),
        ),
    ]
