# Generated by Django 5.1.4 on 2025-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0002_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="rank",
            field=models.JSONField(default=dict),
        ),
    ]
