# Generated by Django 5.1.4 on 2025-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0003_alter_rank_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.URLField(default=None, null=True),
        ),
    ]
