# Generated by Django 4.2.11 on 2025-06-16 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0004_remove_user_password_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contest",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contest",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="contest",
            name="number_of_entries",
            field=models.IntegerField(default=2147483647),
        ),
    ]
