# Generated by Django 5.1.4 on 2025-06-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0005_contest_created_at_contest_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenges",
            old_name="testcase",
            new_name="input_testcase",
        ),
        migrations.RenameField(
            model_name="challenges",
            old_name="output",
            new_name="output_testcase",
        ),
        migrations.RemoveField(
            model_name="challenges",
            name="description",
        ),
    ]
