# Generated by Django 5.1.4 on 2025-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0006_rename_testcase_challenges_input_testcase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="link",
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="contest",
            name="participants",
            field=models.IntegerField(default=0),
        ),
    ]
