# Generated by Django 4.2.11 on 2025-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0007_contest_link_contest_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenges",
            name="cpp_code",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="challenges",
            name="isLeetCode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="challenges",
            name="java_code",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="challenges",
            name="python_code",
            field=models.TextField(default=None, null=True),
        ),
    ]
