# Generated by Django 4.2.11 on 2025-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0008_challenges_cpp_code_challenges_isleetcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="number_of_challenges",
            field=models.IntegerField(default=0),
        ),
    ]
