# Generated by Django 4.2.11 on 2025-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0009_contest_number_of_challenges"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contest_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="contest_participated",
            field=models.IntegerField(default=0),
        ),
    ]
