# Generated by Django 4.2.11 on 2025-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0010_user_contest_created_user_contest_participated"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenges",
            name="leetCodeNumber",
            field=models.TextField(default=None, null=True),
        ),
    ]
