# Generated by Django 5.1.4 on 2025-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0011_challenges_leetcodenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="number_of_participants",
            field=models.IntegerField(default=0),
        ),
    ]
