# Generated by Django 5.1.4 on 2025-02-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='contest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.contest'),
        ),
    ]
