# Generated by Django 5.1.4 on 2025-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0002_score_contest"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="time",
            field=models.TimeField(default=None, null=True),
        ),
    ]
