# Generated by Django 5.1.4 on 2025-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0003_score_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leetcode_Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("description", models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="slug_map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.IntegerField(default=0)),
                ("input", models.TextField(default=None, null=True)),
                ("output", models.TextField(default=None, null=True)),
            ],
        ),
    ]
