# Generated by Django 5.1.4 on 2025-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0004_leetcode_description_slug_map_testcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leetcode_description",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
    ]
