# Generated by Django 4.2.11 on 2025-07-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0005_alter_leetcode_description_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcode_description",
            name="input_description",
            field=models.TextField(default=None, null=True),
        ),
    ]
