# Generated by Django 4.2.11 on 2025-07-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0006_leetcode_description_input_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="solved",
            field=models.IntegerField(default=0),
        ),
    ]
