# Generated by Django 5.1.4 on 2025-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0008_alter_score_solved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="solved",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
